
version: '3.0'

#volumes:
#  db:

services:
  frontend:
    container_name: frontend
    image: golang:latest
    restart: always
    volumes:
      - /home/ubuntu/simple-fortune-cookie/frontend/:/frontend/
    command: bash -c "cd /frontend && go build && go run frontend"
    ports:
     - "8080:8080"
    depends_on:
      - backend

  backend:
    container_name: backend
    image: golang:latest
    volumes:
      - /home/ubuntu/simple-fortune-cookie/backend/:/backend/
    restart: always
    command: bash -c "cd /backend && go build && go run backend"
    ports: 
      - "9000:9000"
#  db:
#    container_name: db
#    image: mysql:5.7
#    volumes:
#      - db:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: wordpress_root_pass
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
  
