
version: '3.0'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    environment:
        BACKEND_DNS: backend
    ports:
     - "8080:8080"
    depends_on:
      - backend
    networks: 
      frontend:

  backend:
    container_name: backend
    build: ./backend
    restart: always
    environment:
        REDIS_DNS: redis
    ports:
     - "9000:9000"
    depends_on:
      - redis
    networks: 
      frontend:
      backend:

  redis:
    container_name: 'redis'
    image: 'redis:latest'
    restart: always
    environment:
       ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./data/redis:/data
    ports: 
      - "6379:6379"
    networks: 
      backend:

networks: 
    frontend:
    backend:
