
version: '3.0'

services:
  frontend:
    container_name: frontend
    image: golang:latest
    restart: always
    volumes:
      - /home/ubuntu/simple-fortune-cookie/frontend/:/frontend/
    command: bash -c "cd /frontend && go build && go run frontend"
    environment:
        BACKEND_DNS: backend
    ports:
     - "8080:8080"
    depends_on:
      - backend
    networks: 
      frontend:

  backend:
    container_name: backend
    image: golang:latest
    volumes:
      - /home/ubuntu/simple-fortune-cookie/backend/:/backend/
    restart: always
    command: bash -c "cd /backend && go build && go run backend"
    ports: 
      - "9000:9000"
    networks: 
      frontend:
      backend:
    environment:
      REDIS_DNS: redis
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports: 
      - "6379:6379"
    networks: 
      backend:

networks: 
    frontend:
    backend:
