name: Deploy Docker images
on: 
  push:
    branches: 
      - main 

jobs:
  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    env:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Push Docker SHA
        run: |
          export GIT_COMMIT="GA-$GITHUB_SHA"
          chmod +x ci/deploy-docker-sha.sh && ci/deploy-docker-sha.sh
      - name: Push Docker latest
        run: |
          export GIT_COMMIT="GA-$GITHUB_SHA"
          chmod +x ci/deploy-docker-latest.sh && ci/deploy-docker-latest.sh