name: Go CI
on: 
  pull_request:
    branches: 
      - main 

jobs:
  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run test
        run: |
          cd frontend
          go test
