name: Go CI
on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Cookie Test
        run: |
          chmod +x frontend/main_test.go 
          go run frontend/ci/main_test.go