name: Go CI
on: 
  pull_request:
    branches: 
      - main 

jobs:
  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run test
        run: |
          cd frontend
          go test

  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    needs: 
      - frontend-test
    env:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set commit variable
        run: |
          export GIT_COMMIT="GA-$GITHUB_SHA"
      - name: Build Docker images
        run: |
          chmod +x ci/build-docker.sh && ci/build-docker.sh
      - name: Deploy to DockerHub
        run: |
          chmod +x ci/push-docker.sh && ci/push-docker.sh


