name: Go CI
on: 
  pull_request:
    branches: 
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Cookie Test
        run: |
          cd frontend
          go test

  docker-push:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Cookie Test
        run: |
          cd frontend
          go test
    env:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}