name: Go CI
on: 
  pull_request:
    branches: 
      - main 

jobs:
  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run test
        run: |
          cd frontend
          go test

  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    depends-on: 
      - frontend-test
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Deploy to DockerHub
        run: |
          docker-compose create
          export GIT_COMMIT="GA-$GITHUB_SHA"
          chmod +x ci/push-docker.sh
          ci/push-docker.sh
    env:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}


