name: Go CI
on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Cookie Test
        run: |
          cd frontend
          go test